[#134618859] Make bbl-mixin-routing-release-lbs take a TERRAFORM_COMMAND argument to allow creation and destruction of lbs

diff --git a/scripts/ci/bbl-mixin-routing-release-lbs/task b/scripts/ci/bbl-mixin-routing-release-lbs/task
--- a/scripts/ci/bbl-mixin-routing-release-lbs/task
+++ b/scripts/ci/bbl-mixin-routing-release-lbs/task
@@ -27,25 +27,31 @@ function main() {
     internal_security_group_id=$(echo "${describe_stacks_output}" | jq -r '.Stacks[].Outputs[] | select(.OutputKey | startswith("Internal")) | select(.OutputValue | startswith("sg-")) | .OutputValue')
     set -x
 
-    echo "Executing specified terraform command..."
-    execute_terraforming "${vpc_id}" "${subnet_ids}"
+    if [ "${TERRAFORM_COMMAND}" == "apply" ]; then
+      terraform_apply "${vpc_id}" "${subnet_ids}"
 
-    set +e
-    git_commit
-    set -e
+      git_commit
 
-    local tcp_router_elb_id
-    tcp_router_elb_id=$(terraform output tcp_router_elb_id)
+      local tcp_router_elb_id
+      tcp_router_elb_id=$(terraform output tcp_router_elb_id)
 
-    local tcp_router_security_group_id
-    tcp_router_security_group_id=$(terraform output tcp_router_security_group_id)
+      local tcp_router_security_group_id
+      tcp_router_security_group_id=$(terraform output tcp_router_security_group_id)
 
-    rm tcp_router_elb.tf
-    if [ -f terraform.tfstate.backup ]; then
-      rm terraform.tfstate.backup
+      rm tcp_router_elb.tf
+      if [ -f terraform.tfstate.backup ]; then
+        rm terraform.tfstate.backup
+      fi
+
+      update_cloud_config "${root_dir}" "${tcp_router_elb_id}" "${tcp_router_security_group_id}" "${internal_security_group_id}"
+    elif [ "${TERRAFORM_COMMAND}" == "destroy" ]; then
+      terraform_destroy "${vpc_id}" "${subnet_ids}"
+      git_commit
+    else
+      echo "Invalid terraform command: \"${TERRAFORM_COMMAND}\""
+      exit 1
     fi
 
-    update_cloud_config "${root_dir}" "${tcp_router_elb_id}" "${tcp_router_security_group_id}" "${internal_security_group_id}"
   popd > /dev/null
 
   shopt -s dotglob
@@ -95,19 +101,38 @@ function git_commit() {
   if [[ -n $(git status --porcelain) ]]; then
     git config user.name "CF MEGA BOT"
     git config user.email "cf-mega@pivotal.io"
+    # TODO: Get rid of this +e -e business in favor of finding a git flag to allow nonzero exit on empty commit
+    set +e
     git add terraform.tfstate
     git commit -m "Commit terraform state file"
+    set -e
   fi
 }
 
-function execute_terraforming() {
+function terraform_apply() {
   local vpc_id
   vpc_id="${1}"
   local subnet_ids
   subnet_ids="${2}"
 
   set +x
-  terraform ${TERRAFORM_COMMAND} -var "access_key=${AWS_ACCESS_KEY_ID}" \
+  terraform apply -var "access_key=${AWS_ACCESS_KEY_ID}" \
+    -var "secret_key=${AWS_SECRET_ACCESS_KEY}" \
+    -var "region=${AWS_DEFAULT_REGION}" \
+    -var "env_name=${ENV_NAME}" \
+    -var "subnet_ids=${subnet_ids}" \
+    -var "vpc_id=${vpc_id}"
+  set -x
+}
+
+function terraform_destroy() {
+  local vpc_id
+  vpc_id="${1}"
+  local subnet_ids
+  subnet_ids="${2}"
+
+  set +x
+  terraform destroy -force -var "access_key=${AWS_ACCESS_KEY_ID}" \
     -var "secret_key=${AWS_SECRET_ACCESS_KEY}" \
     -var "region=${AWS_DEFAULT_REGION}" \
     -var "env_name=${ENV_NAME}" \
