Remove unnecessary backslash in verify-nameserver-has-record task
[#126814171]

Signed-off-by: Dennis Leon <dleon@pivotal.io>

diff --git a/scripts/ci/verify-nameserver-has-record/task b/scripts/ci/verify-nameserver-has-record/task
--- a/scripts/ci/verify-nameserver-has-record/task
+++ b/scripts/ci/verify-nameserver-has-record/task
@@ -5,7 +5,7 @@ set +e
 NS_SEARCH_RESULT="$(nslookup -type=NS ${DOMAIN})"
 set -e
 
-if ! (echo "$NS_SEARCH_RESULT" | grep "server can\'t find"); then
+if ! (echo "$NS_SEARCH_RESULT" | grep "server can't find"); then
   HOSTED_ZONE_FOUND=$(aws --output text route53 list-hosted-zones --query "HostedZones[?Name==\`${DOMAIN}.\`]" | wc -l | awk '{print $1}')
   if [[ $HOSTED_ZONE_FOUND -eq 0 ]]; then
     set +x
